# Site settings
title: mhammarstedt
email: mirandahammarstedt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio page for Miranda Hammarstedt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base.scss hostname & protocol for your site, e.g. http://example.com
github_username:  mhammarstedt
author: Miranda Hammarstedt

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
